spring:
  application:
    name: sales-api
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

sales:
  store-name: Supermarket POS
  tax-rate: 0.19
  freeze-expiration: 2h
  external:
    product-api:
      base-url: http://localhost:8081
      connect-timeout: 2s
      read-timeout: 5s
    customer-api:
      base-url: http://localhost:8082
      connect-timeout: 2s
      read-timeout: 5s
